###
### Rule modifications 
###

included: # case-sensitive paths to include during linting. `--path` is ignored if present
  - Sources
  - Tests
  - Package.swift

identifier_name:
    min_length:
        error: 0
        warning: 0

large_tuple: 5

line_length:
    warning: 200
    error: 500
    ignores_function_declarations: false
    ignores_comments: false
    ignores_urls: true

